### ISSUE TITLE
JavaScript not loading when you have no sidebars switched on

### ISSUE THREAD

**Issue by BenjaminThomson** [wpgaurav/Writ-WordPress-Theme#1]
I think I've found a bug, which I've fixed on my local copy of the code, whereby if you have no "sidebars" switched on then the wp_footer() method doesn;'t get called, so the late loading scripts including the navigation.js which adds the onclick event for the responsive menu.

The error seemed to be in this bit of code in footer.php

`if ( ! is_active_sidebar( 'sidebar-1' ) && ! is_active_sidebar( 'sidebar-2' ) && ! is_active_sidebar( 'sidebar-3' ) ) {
//  return;
}`

I've just removed this code for now from our site as a bit of a hack but thought it was worth reporting. 

Apologies for not  fixing it and submitting a PR but I'm really new to WordPress and didn't know what other situations I might break if I changed it.

**Comment by wpgaurav** [comment]
Thank you for the report. The issue is fixed and more improvements are being made to it.
